### ISSUE TITLE
ROS2 Support

### ISSUE THREAD

**Issue by PranavShevkar** [LTU-RAI/Map-Conversion-3D-Voxel-Map-to-2D-Occupancy-Map#1]
Is there a plan to migrate this repo to ROS2?

**Comment by Scitt** [comment]
Yes, there are plans for ros2 support, but currently, UFOMaps (the voxel mapper currently used by the package) only supports ros1, so we are waiting for it to be updated with ros2 support. 

There are also plans to support other voxel mapping solutions (with support for ros2), but this is currently a low priority.

**Comment by Scitt** [comment]
Support for OctoMap and ROS2 has been added. See the [ros2](https://github.com/LTU-RAI/Map-Conversion-3D-Voxel-Map-to-2D-Occupancy-Map) branch for the ROS2 package.

**Comment by PranavShevkar** [comment]
Thank you
